name: Build and test
on: [workflow_call]
env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  TURBO_REMOTE_ONLY: true
jobs:
  build_and_lint_check:
    name: ğŸ” Typecheck
    uses: ./.github/workflows/build-reusable.yml
    with:
      afterBuild: pnpm typecheck
    secrets: inherit
  quality:
    name: ğŸ” Ensure that the code meets our quality standard
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v1
        with:
          version: latest
      - name: Run Biome
        run: biome ci .
  test-integration-dev:
    name: âš«ï¸ Run Jest (development mode) integration tests
    uses: ./.github/workflows/build-reusable.yml
    with:
      afterBuild: |
        NEXT_TEST_MODE=dev pnpm test -- -- __tests__/integration --ci --runInBand
    secrets: inherit
  test-integration-prod:
    name: âš«ï¸ Run Jest (production mode) integration tests
    uses: ./.github/workflows/build-reusable.yml
    with:
      afterBuild: |
        NEXT_TEST_MODE=start pnpm test -- -- __tests__/integration --ci --runInBand
    secrets: inherit
  test-e2e-dev:
    name: âš«ï¸ Run Jest (development mode) E2E tests
    uses: ./.github/workflows/build-reusable.yml
    with:
      afterBuild: |
        NEXT_TEST_MODE=dev pnpm test -- -- __tests__/e2e --ci --runInBand
    secrets: inherit
  test-e2e-prod:
    name: âš«ï¸ Run Jest (production mode) E2E tests
    uses: ./.github/workflows/build-reusable.yml
    with:
      afterBuild: |
        NEXT_TEST_MODE=start pnpm test -- -- __tests__/e2e --ci --runInBand
    secrets: inherit
