name: Build and test
on: [workflow_call]
env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  TURBO_REMOTE_ONLY: true
jobs:
  build_and_lint_check:
    name: ğŸ” Typecheck, check formatting and lint
    uses: ./.github/workflows/build-reusable.yml
    with:
      afterBuild: |
        pnpm typecheck &&
        pnpm format:check &&
        pnpm lint &&
        pnpm docs:lint
    secrets: inherit
  test-dev:
    name: âš«ï¸ Run Jest (development mode) tests
    uses: ./.github/workflows/build-reusable.yml
    with:
      afterBuild: |
        NEXT_TEST_MODE=dev pnpm jest __tests__/e2e --ci --runInBand
    secrets: inherit
  test-prod:
    name: âš«ï¸ Run Jest (production mode) tests
    uses: ./.github/workflows/build-reusable.yml
    with:
      afterBuild: |
        NEXT_TEST_MODE=start pnpm jest __tests__/e2e --ci --runInBand
    secrets: inherit
